### ISSUE TITLE
Now this is epic.

### ISSUE THREAD

**Issue by ghost** [RepComm/webmc#2]
that's all, i just wanted to say how epic it is. but you disappeared on discord so i had to come here. looking forward to seeing what you do with Minecraft in a web browser!

**Comment by ghost** [comment]
wait you might not see this if i close it hold on-

**Comment by RepComm** [comment]
lol thanks. the story on the discord thing is that I've been fed up with centralized stuff, and found element.io (which could be better but is better than discord), and session messenger (which is still new and buggy, but also extreme end of decentralized and anonymous).

I've contemplated getting back onto discord strictly for work and software dev.

if you're interested in helping me work on this let me know, I'd love the help!
